import type { Metadata } from "next"
import CssBaseline from "@mui/material/CssBaseline"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import { Box } from "@mui/material"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CssBaseline enableColorScheme />
        <AppRouterCacheProvider>
          <Box marginY={16}>{children}</Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
